- name: Install fail2ban
  apt:
    pkg:
      - fail2ban
- name: Copy /etc/fail2ban/jail.local
  copy:
    src: files/etc/fail2ban-jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
    owner: root
    group: root
  notify:
    - fail2banRestart
- name: Enable fail2ban
  systemd:
    name: fail2ban.service
    enabled: true
    state: started
